- name: Play 2
  hosts: windows1
  gather_facts: false
  connection: local
  tasks:
    - name: excute command 'create account'
      ansible.netcommon.telnet:
        user: student
        password: p@ssw0rd
        login_prompt: "login:"
        password_prompt: "password:"
        prompts:
          - '[#]'
        command: 
          - net user DesktopUser1 WGU123 /add
